apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuber-rs-1
  labels:
    app: kuber-rs
spec:
  replicas: 4
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - name: kuber-app
          image: skhandorin/hw2:v1.0
          imagePullPolicy: IfNotPresent
